# Generated by Django 5.1.1 on 2024-10-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_videocategory_videolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('video_name', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('video_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.videocategory')),
                ('video_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.videolocation')),
            ],
        ),
    ]
